### ISSUE TITLE
Display rotation is not taken into account on hyprland

### ISSUE THREAD

**Issue by Beyley** [galister/wlx-overlay-s#105]
Doesn't seem to be a hyprland issue as monitors are correct in OBS

![image](https://github.com/user-attachments/assets/f2056e6d-d2ec-4d35-a226-f8cd8d10d0a3)

**Comment by galister** [comment]
Hi, this is because the default capture method on hyprland is zwlr-dmabuf, and that returns the raw texture, without respecting rotation.

Try forcing pipewire:
`echo 'capture_method: pipewire' > ~/.config/wlxoverlay/conf.d/pw_fallback.yaml`

**Comment by Beyley** [comment]
That does not seem to fix the issue

**Comment by galister** [comment]
mind dropping the logs from `/tmp/wlx.log`?

**Comment by Beyley** [comment]
[wlx.log](https://github.com/user-attachments/files/17796269/wlx.log)

**Comment by Beyley** [comment]
Sadly the issue still occurs 
[wlx.log](https://github.com/user-attachments/files/17827418/wlx.log)

**Comment by galister** [comment]
is it also wrong if you try:
`echo 'capture_method: screencopy' > ~/.config/wlxoverlay/conf.d/pw_fallback.yaml`
?

**Comment by Beyley** [comment]
that renders it correctly, but the performance is very poor (feels like 3-8fps)

**Comment by galister** [comment]
does this work better?
`echo 'capture_method: wlr-dmabuf' > ~/.config/wlxoverlay/conf.d/pw_fallback.yaml`

this used to be the default, but some people reported instability, so i made pipewire the default. then people started reporting instability with pipewire, i think it was the amdgpu driver all along, as i don't get instabilities with either anymore, but in case your desktop crashes, it's likely due to `wlr-dmabuf`.

**Comment by Beyley** [comment]
Fixed in 3b3138cfe99adeaebbb3da7e844c7d69183aaa77 when using `pipewire` capture
